export {
    cibGit,
    cilAccountLogout,
    cilApplications,
    cilBarcode,
    cilCheck,
    cilCheckCircle,
    cilCog,
    cilContrast,
    cilCopy,
    cilEnvelopeClosed,
    cilExternalLink,
    cilFlip,
    cilHamburgerMenu,
    cilHome,
    cilLockLocked,
    cilMoon,
    cilPencil,
    cilPeople,
    cilPlus,
    cilSpreadsheet,
    cilSun,
    cilSync,
    cilUserPlus,
    cilWarning,
    cilX,
    cilXCircle,
} from '@coreui/icons';
